### ISSUE TITLE
Where one can find X11 Window Manager on C#?

### ISSUE THREAD

**Issue by ArsenShnurkov** [frankhale/xsharp#1]
Or is there something for Wayland?

http://www.reddit.com/r/linux/comments/1mx7qr/is_it_possible_to_program_an_x11_window_manager/

**Comment by frankhale** [comment]
I don't know what others may have done so cannot comment there.

XSharp was never finished but it's absolutely possible to write a window manager in C#. XSharp was an attempt to wrap all the necessary functions and structures of X11 (Xlib) so that they are usable from C# or any other .NET language.
